name: scott_and_viki
description: White label wedding app

dependencies:
  map_view: ^0.0.12
  image_picker: ^0.4.1
  url_launcher: ^3.0.0
  firebase_storage: ^0.3.4
  firebase_database: ^0.4.6
  shared_preferences: ^0.4.1
  camera: ^0.2.0
  video_player: ^0.5.3
  path_provider: ^0.4.0
  connectivity: ^0.3.0
  zoomable_image: ^1.2.0
  json_annotation: ^0.2.4
  firebase_messaging: ^1.0.0
  image: ^1.1.33
  path: ^1.5.1
  uuid: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
          sdk: flutter

dev_dependencies:
  build_runner: ^0.8.0
  json_serializable: ^0.5.2
  flutter_launcher_icons: ^0.3.2
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: assets/icon.jpg
  android: true
  ios: true

flutter:
  fonts:
    - family: CallingAngelsPersonalUse
      fonts:
        - asset: fonts/CallingAngelsPersonalUse.ttf
    - family: DancingScript-Regular
      fonts:
        - asset: fonts/DancingScript-Regular.ttf
    - family: Strawberry_Whipped_Cream
      fonts:
        - asset: fonts/Strawberry_Whipped_Cream.ttf

  assets:
    - background.png
    - SVSunset.jpg
    - 1.jpg
    - 2.jpg
    - 3.jpg
    - 4.jpg
    - 5.jpg
    - 6.jpg
    - 7.jpg
    - backIcon.png
    - churchLocation.png
    - farmLocation.png
    - icon.jpg

  uses-material-design: true
