name: scott_and_viki
description: White label wedding app

dependencies:
  map_view: ^0.0.12
  image_picker: ^0.4.1
  url_launcher: ^3.0.0
  shared_preferences: ^0.4.1
  firebase_storage: ^0.3.4
  flutter:
    sdk: flutter
  flutter_localizations:
          sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: CallingAngelsPersonalUse
      fonts:
        - asset: fonts/CallingAngelsPersonalUse.ttf
    - family: DancingScript-Regular
      fonts:
        - asset: fonts/DancingScript-Regular.ttf
    - family: Strawberry_Whipped_Cream
      fonts:
        - asset: fonts/Strawberry_Whipped_Cream.ttf

  assets:
    - assets/background.png
    - assets/SVSunset.jpg
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.jpg
    - assets/6.jpg
    - assets/7.jpg
    - backIcon.png
    - churchLocation.png
    - farmLocation.png

  uses-material-design: true
